[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

# Change the `name` of this constraint to be the import path of the upstream
# Terraform provider, and set the `version` to be the tag name of the release
# you wish to pin to.
#
# If it is necessary to fork the provider, set the `name` to the canonical import
# path (i.e. github.com/terraform-providers/terraform-provider-x), and set the
# `source` to the fork address. Then set the `branch` to `pulumi-master` in the
# fork, and ensure `version` is not set.
[[constraint]]
  version = "v1.4.1"
  name = "github.com/terraform-providers/terraform-provider-packet"

  [constraint.metadata]
    gomod-override = true
    gomod-exclude-prefixes = [
      "github.com/golang/protobuf",
    ]


# NOTE: this Gopkg.toml file was constructed using gomod-override

[[override]]
  name = "github.com/agext/levenshtein"
  version = "=v1.2.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "7e4b007599d4e2076d9a81be723b3912852dda2c"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-textseg"
  revision = "b836f5c4d331d1945a2fead7188db25432d73b69"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/armon/go-radix"
  revision = "1fca145dffbcaa8fe914309b1ec0cfc67500fe61"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.8.34"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/bgentry/speakeasy"
  version = "=v0.1.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/blang/semver"
  version = "=v3.5.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/go-ini/ini"
  version = "=v1.23.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/gopherjs/gopherjs"
  revision = "d547d1d9531ed93dbdebcbff7f83e7c876a1e0ee"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "3573b8b52aa7b37b9358d966a898feb387f62437"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-getter"
  revision = "a686900cb3753aa644dc4812be91ceaf9fdd3b98"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-hclog"
  revision = "8105cc0a3736cc153a2025f5d0d91b80045fc9ff"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f09973e19c1dfcd120b2d9c4f168e68d6b5d5"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "a5174f84d7f8ff00fb07ab4ef1f380d32eee0e63"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-uuid"
  revision = "36289988d83ca270bc07c234c36f364b0dd9c9a7"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-version"
  revision = "e96d3840402619007766590ecea8dd7af1292276"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl"
  revision = "a4b07c25de5ff55ad3b8936cea69a79a3d95a855"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl2"
  revision = "44bad6dbf5490f5da17ec991e664df3d017b706f"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/hil"
  revision = "fac2259da677551de1fb92b844c4d020a38d8468"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/logutils"
  revision = "0dc08b1671f34c4250ce212759ebd880f743d883"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/terraform"
  version = "=v0.11.3"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/yamux"
  revision = "d1caa6c97c9fc1cc9e83bbe34d0603f9ff0ce8bd"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/jtolds/gls"
  version = "=v4.2.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/kylelemons/godebug"
  revision = "d65d576e9348f5982d7f6d83682b694e731a45c6"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mattn/go-isatty"
  version = "=v0.0.2"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/cli"
  revision = "0ce7cd515f64496ee660ab19f6bbf373945d3af0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/copystructure"
  revision = "5af94aef99f597e6a9e1f6ac6be6ce0f3c96b49d"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/go-testing-interface"
  revision = "a61a99592b77c9ba629d254a693acffaeb4b7e28"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/hashstructure"
  revision = "6b17d669fac5e2f71c16658d781ec3fdd3802b69"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "53818660ed4955e899c0bcafa97299a388bd7c8e"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "92573fe8d000a145bfebc03a16bc22b34945867f"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/packethost/packngo"
  revision = "caf7bb8cb1044343747215c54e45a01dbb41c8a2"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/posener/complete"
  revision = "9f41f7636a724791a3b8b1d35e84caa1124f0d3c"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "b061729afc07e77a8aa4fad0a2fd840958f1942a"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/smartystreets/assertions"
  revision = "b6c0e53d73045618965505ac26ff7864fe3ab2b2"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/smartystreets/goconvey"
  revision = "044398e4856c3a83fb98f9de0a8ed1c6495e2843"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/ulikunitz/xz"
  version = "=v0.5.4"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/zclconf/go-cty"
  revision = "49fa5e03c418f95f78684c91e155af06aa901a32"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "golang.org/x/net"
  revision = "d25186b37f34ebdbbea8f488ef055638dfab272d"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "golang.org/x/sync"
  revision = "37e7f081c4d4c64e13b10787722085407fe5d15f"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "golang.org/x/text"
  revision = "b7ef84aaf62aa3e70962625c80a571ae7c17cb40"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "google.golang.org/genproto"
  revision = "595979c8a7bf586b2d293fb42246bf91a0b893d9"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "google.golang.org/grpc"
  revision = "91999f444f2aa89f2f873c8429a424701309bec4"
  [override.metadata]
    gomod-overridden=true
